# kubectl -n default create secret generic test --from-literal=TEST_KEY="testvalue"
apiVersion: v1
kind: Secret
metadata:
  name: secret-account
data:
  ACCOUNT: YmVv
type: Opaque

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: secrets-volume
  volumes:
  - name: secrets-volume
    secret:
      secretName: secret-account
      items:
      - key: ACCOUNT
        path: index.html