apiVersion: v1
kind: Service
metadata:
  labels:
    app: node
  name: web-svc
  namespace: default
spec:
  ports:
  - port: 5566
    protocol: TCP
    targetPort: 5566
  selector:
    app: node
  sessionAffinity: None