apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: default
  labels:
    app: node
spec:
  containers:
  - image: google/golang-hello
    imagePullPolicy: Always
    name: node
    ports:
      - containerPort: 5566
        protocol: TCP
    env:
    - name: PORT
      value: "5566"